### PR TITLE
Fixed the issue were the trailpack doesn't emit the `webserver:http:r…

### PR DESCRIPTION
**Pull request by weyert**
…eady`-event other trailpacks are expecting this event to be triggered e.g.`trailpack-realtime`.

See also ticket: https://github.com/trailsjs/trailpack-realtime/issues/6

### CODE REVIEW

**Comment by jaumard** [comment]
Thanks @weyert don't know why this piece of code has disappear... Can you fix eslint error ? And also modify this code to be send same element as `trailpack-express` (https://github.com/trailsjs/trailpack-realtime/pull/7#issuecomment-239665114)

**Comment by weyert** [comment]
I have updated the code. I am not sure about which ESLint error you are referring too. The node package doesn't come with it.

**Comment by jaumard** [comment]
@weyert thanks ! Continuous integration on TravisCI is failing you can see errors here https://travis-ci.org/trailsjs/trailpack-hapi/jobs/152783889#L299-L300

**Comment by konstantinzolotarev** [comment]
@weyert just remove semicolons after lines 62, 66

**Comment by weyert** [comment]
Done!

**Comment by jaumard** [comment]
Thanks @weyert :)

**Comment by weyert** [comment]
Thank you!

**Pull request merged**
