### PR TITLE
multiple static paths

### PR DESCRIPTION
**Pull request by imkarma**
Allow user multiple static path

``` javascript
www: [
      {
        path: path.resolve(__dirname, '..', 'static'),
        humanUrl: '/admin'
      },
      {
        path: path.resolve(__dirname, '..', 'uploads'),
        humanUrl: '/imagestatic'
      }
    ]
```

link to pull request needed to approv what would it work - [#56](https://github.com/trailsjs/trailpack-core/pull/56)

### CODE REVIEW

**Comment by konstantinzolotarev** [comment]
@imkarma Could you please fix conflicts ?

**Comment by imkarma** [comment]
@konstantinzolotarev you mean eslint? or what? :)

**Comment by konstantinzolotarev** [comment]
@imkarma Oh sorry. wrong issue =)

**Comment by konstantinzolotarev** [comment]
@imkarma Could you please also update docs with this feature ?

**Pull request merged**
