### PR TITLE
restored working assets config

### PR DESCRIPTION
**Pull request by weyj4**

### CODE REVIEW

**Comment by weyj4** [comment]
In between these two commits lib/server got reverted to an earlier (dysfunctional) version:
https://github.com/trailsjs/trailpack-hapi/blob/3c8322a0ecf6fffcf978687723365add7889ffcd/lib/server.js#L52
https://github.com/trailsjs/trailpack-hapi/tree/517df9a8d3683feb6409b04df42d6d66bfe16331

**Comment by weyj4** [comment]
@tjwebb did you mean to revert those changes?

also not sure what's up with travis-ci

**Comment by tjwebb** [comment]
Weird, what was the issue you ran into? I changed the path resolution because using `/` won't work on Windows.

**Comment by tjwebb** [comment]
The deal with travis-ci I think is this:

> Now using node v6.0.0 (npm v3.8.6)

**Comment by wbprice** [comment]
@tjwebb this PR was opened because I ran into trouble grabbing static assets from `static/bundle.js` with this config in `main.js`:

``` js
  paths: {
    root: path.resolve(__dirname, '..'),
    temp: path.resolve(__dirname, '..', '.tmp'),
    www: path.resolve(__dirname, '..', 'static')
  }
```

Was there an API change?

**Comment by weyj4** [comment]
@tjwebb @wbprice 
Today I learned: node's path module has "path.sep", which is OS-agnostic :)

This PR should be good to go but I guess I should write tests for it before sending it to npm. In the meantime though this trailpack doesn't serve static directories.

**Pull request merged**
