### PR TITLE
updated travis

### PR DESCRIPTION
**Pull request by weyj4**

### CODE REVIEW

**Comment by weyj4** [comment]
@tjwebb working on getting these tests to pass...you have any idea what's up with travis-ci? I updated it to node 6.

**Comment by jaumard** [comment]
@weyj4 TravisCI break because the sqlite3 version use by waterline is not compatible with node 6, `trailpack-waterline` need to be updated to last sqlite3 version (ut first the adapter see my PR https://github.com/waterlinejs/sqlite3-adapter/pull/10).
Travis have to run on node 4, 5, and 6 and deploy on 6 like this https://github.com/trailsjs/trailpack-router/blob/master/.travis.yml#L24 stable is not deprecated.

**Comment by weyj4** [comment]
OK. Is there anything you need help with to make sqlite3 work? Are we just waiting on a PR?

**Comment by jaumard** [comment]
@weyj4 yes my PR on sliqte3 adapter fix node 6 issue, I also publish a new version of trailpack-waterline who doesn't use sqlite3. If you need an adapter on your tests use `sails-disk` and like this no more problem with Travis. You can check what I've done on Express trailpack

**Pull request closed without merging**
