### PR TITLE
added pug as dev dependency

### PR DESCRIPTION
**Pull request by weyj4**

### CODE REVIEW

**Comment by jaumard** [comment]
Why keep it if it's not use at all on code ?

**Comment by weyj4** [comment]
why is it in express?

**Comment by jaumard** [comment]
For unit testing about rendering views https://github.com/trailsjs/trailpack-express/blob/master/test/app.js#L122 and https://github.com/trailsjs/trailpack-express/blob/master/test/api/controllers/ViewController.js#L6

**Comment by weyj4** [comment]
It looks like the only package that requires jade is mocha. So yeah, I'll get rid of pug here but not sure what I can do to fix the jade warning

**Pull request closed without merging**
